PIX minimun value warning
cloudwalk/infinitepay-woocommerce-plugin pull request #42
Opened 2022-11-30 11:10 UTC by malkafly-cw

Added a warning when the payment amount is less than BRL 1.00 in the PIX

![image](https://user-images.githubusercontent.com/110417662/204779421-dc8a7c95-5762-40e7-a122-a2a6a3346fca.png)

2022-12-02 12:54 UTC, panachi-cw approved these changes
42

2022-12-02 13:31 UTC, bru-carenzi requested changes
### Test Summary

**Status**:  👎 Not recommended 

---


📋 Test report 
Insert here which tests you have done in this PR and put a ✅ [Check Mark Button](https://emojipedia.org/check-mark-button/) emoji for those tests that are validated, or put the [❌ Cross Mark](https://emojipedia.org/cross-mark/) for the tests with error.

* Amount less than 1,00 should appears the warning - ✅ 
* Amount == 1,00 should not appears the warning - ❌
* Amount > 1,00 should not appears the warning - ✅ 

🙆‍♀️ Non-block issues
# 

🙅 Block issues
It's not been accepting amount == 1,00  to pay with Pix.

2022-12-06 11:43 UTC, malkafly-cw commented on src/Controller/Checkout.php
> +			if( $final_value < 101 ) {
Oh! I misunderstood the rule, I thought it was above 1, I will fix it now. Thanks!

2022-12-06 12:37 UTC, bru-carenzi approved these changes
### Test Summary

**Status**: ready 

---


📋 Test report 
Insert here which tests you have done in this PR and put a ✅ [Check Mark Button](https://emojipedia.org/check-mark-button/) emoji for those tests that are validated, or put the [❌ Cross Mark](https://emojipedia.org/cross-mark/) for the tests with error.

Pix amount < 1,00: 
* Warning when the amount is < 1,00 - ✅ 
* Warning does not show up when the amount is >= 1,00 - ✅ 
* Pix Payment - ✅

2022-12-06 13:35 UTC, panachi-cw approved these changes

2022-12-06 13:42 UTC, bru-carenzi reviewed
@malkafly-cw could u implement character limits in the CPF field to 11 numbers, pls?
Also, we need to apply the item 3 for this field as well: 3. Campos numéricos de cartão devem der o type number (exibir teclado no mobile)
From a mobile device the CPF field accept letters and number and has not limit:

[CHECK THE IMAGE](https://user-images.githubusercontent.com/93997860/205922112-9f32782e-f32e-4b98-b16e-33fcff67befe.png)

Pedidos PIX não mudam de status na loja, mesmo após ser aprovado na InfinitePay

In the tests the order after be approved change the status to "Processando" and when this order has not payment, the status is "Pagemento pendente". The same happens to credit card payment, this is the expect behavior? cc: @malkafly-cw @panachi-cw

Also, we need to fix this problem: https://github.com/cloudwalk/product-ecommerce/issues/67

2022-12-06 13:47 UTC, bru-carenzi requested changes
### Test Summary

**Status**:  👎 Not recommended 

---

2022-12-07 11:56 UTC, malkafly-cw commented
@bru-carenzi the css, numeric field on CPF and log pix webhook are implemented and ready to test

2022-12-08 13:35 UTC, panachi-cw approved these changes
Update the changelog

2022-12-12 21:54 UTC, merged